/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cec_LibCEC */

#ifndef _Included_cec_LibCEC
#define _Included_cec_LibCEC
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cec_LibCEC
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cec_LibCEC_init
  (JNIEnv *, jobject);

/*
 * Class:     cec_LibCEC
 * Method:    Open
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_cec_LibCEC_open
  (JNIEnv *, jobject, jstring);

/*
 * Class:     cec_LibCEC
 * Method:    getAdapters
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_cec_LibCEC_getAdapters
  (JNIEnv *, jobject);

/*
 * Class:     cec_LibCEC
 * Method:    powerOnDevice
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_cec_LibCEC_powerOnDevice
  (JNIEnv *, jobject, jint);

/*
 * Class:     cec_LibCEC
 * Method:    powerOnTV
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_cec_LibCEC_powerOnTV
  (JNIEnv *, jobject);

/*
 * Class:     cec_LibCEC
 * Method:    getActiveDevices
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_cec_LibCEC_getActiveDevices
  (JNIEnv *, jobject);

/*
 * Class:     cec_LibCEC
 * Method:    getDeviceVendorId
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_cec_LibCEC_getDeviceVendorId
  (JNIEnv *, jobject, jint);

/*
 * Class:     cec_LibCEC
 * Method:    getDevicePowerStatus
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_cec_LibCEC_getDevicePowerStatus
  (JNIEnv *, jobject, jint);

/*
 * Class:     cec_LibCEC
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cec_LibCEC_close
   (JNIEnv *, jobject);

/*
 * Class:     cec_LibCEC
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cec_LibCEC_dispose
   (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
